### ISSUE TITLE
Error running tests

### ISSUE THREAD

**Issue by matthiaskoenig** [janekg89/flutype_webapp#35]
I get the following errors
```
mkoenig@core1:~/git/flutype_webapp$ python manage.py test
****************************************
RUNNING IN DEVELOP
****************************************
/home/mkoenig/git/flutype_webapp
Creating test database for alias 'default'...
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mkoenig/envs/flutype_webapp_py27/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/mkoenig/envs/flutype_webapp_py27/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/mkoenig/envs/flutype_webapp_py27/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/home/mkoenig/envs/flutype_webapp_py27/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/mkoenig/envs/flutype_webapp_py27/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/mkoenig/envs/flutype_webapp_py27/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/mkoenig/envs/flutype_webapp_py27/local/lib/python2.7/site-packages/django/test/runner.py", line 601, in run_tests
    old_config = self.setup_databases()
  File "/home/mkoenig/envs/flutype_webapp_py27/local/lib/python2.7/site-packages/django/test/runner.py", line 546, in setup_databases
    self.parallel, **kwargs
  File "/home/mkoenig/envs/flutype_webapp_py27/local/lib/python2.7/site-packages/django/test/utils.py", line 187, in setup_databases
    serialize=connection.settings_dict.get('TEST', {}).get('SERIALIZE', True),
  File "/home/mkoenig/envs/flutype_webapp_py27/local/lib/python2.7/site-packages/django/db/backends/base/creation.py", line 77, in create_test_db
    self.connection._test_serialized_contents = self.serialize_db_to_string()
  File "/home/mkoenig/envs/flutype_webapp_py27/local/lib/python2.7/site-packages/django/db/backends/base/creation.py", line 121, in serialize_db_to_string
    serializers.serialize("json", get_objects(), indent=None, stream=out)
  File "/home/mkoenig/envs/flutype_webapp_py27/local/lib/python2.7/site-packages/django/core/serializers/__init__.py", line 129, in serialize
    s.serialize(queryset, **options)
  File "/home/mkoenig/envs/flutype_webapp_py27/local/lib/python2.7/site-packages/django/core/serializers/base.py", line 80, in serialize
    for count, obj in enumerate(queryset, start=1):
  File "/home/mkoenig/envs/flutype_webapp_py27/local/lib/python2.7/site-packages/django/db/backends/base/creation.py", line 117, in get_objects
    for obj in queryset.iterator():
  File "/home/mkoenig/envs/flutype_webapp_py27/local/lib/python2.7/site-packages/polymorphic/query.py", line 42, in _polymorphic_iterator
    o = next(base_iter)
  File "/home/mkoenig/envs/flutype_webapp_py27/local/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/home/mkoenig/envs/flutype_webapp_py27/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 894, in execute_sql
    raise original_exception
django.db.utils.OperationalError: no such column: flutype_ligand.polymorphic_ctype_id
```

**Comment by matthiaskoenig** [comment]
On the laptop the following
```
Creating test database for alias 'default'...
Traceback (most recent call last):
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: flutype_ligand

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/core/management/commands/test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/core/management/commands/test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/test/runner.py", line 601, in run_tests
    old_config = self.setup_databases()
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/test/runner.py", line 546, in setup_databases
    self.parallel, **kwargs
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/test/utils.py", line 187, in setup_databases
    serialize=connection.settings_dict.get('TEST', {}).get('SERIALIZE', True),
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/db/backends/base/creation.py", line 77, in create_test_db
    self.connection._test_serialized_contents = self.serialize_db_to_string()
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/db/backends/base/creation.py", line 121, in serialize_db_to_string
    serializers.serialize("json", get_objects(), indent=None, stream=out)
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/core/serializers/__init__.py", line 129, in serialize
    s.serialize(queryset, **options)
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/core/serializers/base.py", line 80, in serialize
    for count, obj in enumerate(queryset, start=1):
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/db/backends/base/creation.py", line 117, in get_objects
    for obj in queryset.iterator():
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/polymorphic/query.py", line 42, in _polymorphic_iterator
    o = next(base_iter)
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 894, in execute_sql
    raise original_exception
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 884, in execute_sql
    cursor.execute(sql, params)
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: flutype_ligand
```

**Comment by matthiaskoenig** [comment]
The issue could be due to the sqlite3 file being written/read with different sqlite versions depending on the underlying python version (sqlite3 is part of python, but depending on the python version different sqlite3 could be installed)
On my laptop I have the following combination.
```
~/git/flutype_webapp$ python
Python 3.6.2 (default, Jul 20 2017, 08:43:29) 
[GCC 5.4.1 20170519] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> sqlite3.version_info
(2, 6, 0)
>>> sqlite3.sqlite_version_info
(3, 11, 0)
```

**Comment by matthiaskoenig** [comment]
The issue could be due to the sqlite3 file being written/read with different sqlite versions depending on the underlying python version (sqlite3 is part of python, but depending on the python version different sqlite3 could be installed)
On my laptop I have the following combination.
```
~/git/flutype_webapp$ python
Python 3.6.2 (default, Jul 20 2017, 08:43:29) 
[GCC 5.4.1 20170519] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> sqlite3.version_info
(2, 6, 0)
>>> sqlite3.sqlite_version_info
(3, 11, 0)
```

**Comment by matthiaskoenig** [comment]
Figured this out.
One has to make sure that the migrations are up to date and in sync with the database. Before running the tests the migrations are applied. If these are out of date some obscure errors occur. 
On the travis server no migrations exist, so the tests work.

Solution: delete or update the local migrations (not tracked in git).
