### ISSUE TITLE
Missing bootstrap_jinja requirement

### ISSUE THREAD

**Issue by matthiaskoenig** [janekg89/flutype_webapp#47]
I am getting the following errors with the latest develop branch locally, 
just saw the same issue in the travis report.
Probably missing requirements in `requirements.txt`. Always add the requirements if you use new packages. 

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f9dc5896950>
Traceback (most recent call last):
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/utils/autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/home/mkoenig/envs/flutype_webapp/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'bootstrapform_jinja'
```

**Comment by matthiaskoenig** [comment]
This is resolved.
